# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 876)
        MainWindow.setStyleSheet("/* GLOBAL DARK THEME */\n"
"* {\n"
"    font-family: \"Segoe UI\", Roboto, Arial, sans-serif;\n"
"}\n"
"QMainWindow {\n"
"    background-color: #121212;\n"
"}\n"
"QWidget#centralwidget {\n"
"    background-color: #121212;\n"
"}\n"
"QLabel {\n"
"    color: #E0E0E0;\n"
"}\n"
"/* PANELS & TITLE BAR */\n"
"QFrame#title_bar {\n"
"    background-color: #1A1A2E;\n"
"    border-bottom: 2px solid #282846;\n"
"}\n"
"QFrame#frame_settings_panel {\n"
"    background-color: #1A1A2E;\n"
"    border-radius: 8px;\n"
"    border: 1px solid #333333;\n"
"}\n"
"QGroupBox {\n"
"    background-color: #1E1E1E;\n"
"    border: 1px solid #333333;\n"
"    border-radius: 6px;\n"
"    margin-top: 12px;\n"
"    padding-top: 15px;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 10px;\n"
"    color: #00E676;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"/* NAVIGATION BUTTONS */\n"
"QPushButton#btn_nav_inspection {\n"
"    background-color: #00E676;\n"
"    color: #121212;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"    padding: 8px 16px;\n"
"}\n"
"QPushButton#btn_nav_settings {\n"
"    background-color: #333333;\n"
"    color: #AAAAAA;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"    padding: 8px 16px;\n"
"}\n"
"QPushButton#btn_nav_settings:hover { background-color: #444444; color: white; }\n"
"\n"
"/* GENERAL BUTTONS */\n"
"QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: white;\n"
"    border: 1px solid #444444;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover { background-color: #3D3D3D; border-color: #00E676; }\n"
"QPushButton:pressed { background-color: #1E1E1E; }\n"
"\n"
"/* ACTION BUTTONS (INSPECTION PAGE) */\n"
"QPushButton#btn_start { background-color: #00C853; border: none; font-size: 16px; font-weight: bold; color: white; border-radius: 8px;}\n"
"QPushButton#btn_start:hover { background-color: #00E676; }\n"
"QPushButton#btn_reset { background-color: #FDD835; border: none; font-size: 16px; font-weight: bold; color: #121212; border-radius: 8px;}\n"
"QPushButton#btn_reset:hover { background-color: #FFEE58; }\n"
"QPushButton#btn_stop { background-color: #E53935; border: none; font-size: 16px; font-weight: bold; color: white; border-radius: 8px;}\n"
"QPushButton#btn_stop:hover { background-color: #EF5350; }\n"
"\n"
"QPushButton#btn_add_log { background-color: #00C853; border:none; font-weight:bold; }\n"
"QPushButton#btn_delete_log { background-color: #E53935; border:none; font-weight:bold; }\n"
"\n"
"/* INPUTS & CONTROLS (SETTINGS PAGE) */\n"
"QComboBox {\n"
"    background-color: #222222;\n"
"    color: white;\n"
"    border: 1px solid #444444;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    font-size: 13px;\n"
"}\n"
"QComboBox::drop-down { border: none; }\n"
"QLineEdit {\n"
"    background-color: #121212;\n"
"    color: #00E676;\n"
"    border: 1px solid #444444;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"QRadioButton, QCheckBox {\n"
"    color: #E0E0E0;\n"
"    spacing: 8px;\n"
"}\n"
"QRadioButton::indicator, QCheckBox::indicator {\n"
"    width: 16px; height: 16px;\n"
"}\n"
"\n"
"/* LCD NUMBERS */\n"
"QLCDNumber {\n"
"    background-color: #0A0A0A;\n"
"    color: #00E676;\n"
"    border: 1px solid #333333;\n"
"    border-radius: 4px;\n"
"}\n"
"/* TABLE WIDGET */\n"
"QTableWidget {\n"
"    background-color: #181818;\n"
"    alternate-background-color: #222222;\n"
"    color: #E0E0E0;\n"
"    gridline-color: #333333;\n"
"    border: 1px solid #333333;\n"
"    border-radius: 4px;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #1A1A2E;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 4px;\n"
"    border: 1px solid #333333;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(10, 10, 10, 10)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.title_bar = QtWidgets.QFrame(parent=self.centralwidget)
        self.title_bar.setMinimumSize(QtCore.QSize(0, 80))
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 80))
        self.title_bar.setObjectName("title_bar")
        self.title_layout = QtWidgets.QHBoxLayout(self.title_bar)
        self.title_layout.setObjectName("title_layout")
        self.logo_frame = QtWidgets.QFrame(parent=self.title_bar)
        self.logo_frame.setMinimumSize(QtCore.QSize(60, 60))
        self.logo_frame.setMaximumSize(QtCore.QSize(60, 60))
        self.logo_frame.setStyleSheet("background-color: #E53935; border-radius: 8px;")
        self.logo_frame.setObjectName("logo_frame")
        self.logo_layout = QtWidgets.QVBoxLayout(self.logo_frame)
        self.logo_layout.setObjectName("logo_layout")
        self.lbl_logo = QtWidgets.QLabel(parent=self.logo_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(True)
        self.lbl_logo.setFont(font)
        self.lbl_logo.setStyleSheet("color: white; background: transparent;")
        self.lbl_logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_logo.setObjectName("lbl_logo")
        self.logo_layout.addWidget(self.lbl_logo)
        self.title_layout.addWidget(self.logo_frame)
        self.titles_layout = QtWidgets.QVBoxLayout()
        self.titles_layout.setSpacing(2)
        self.titles_layout.setObjectName("titles_layout")
        self.lbl_title = QtWidgets.QLabel(parent=self.title_bar)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("color: #E53935;")
        self.lbl_title.setObjectName("lbl_title")
        self.titles_layout.addWidget(self.lbl_title)
        self.lbl_subtitle = QtWidgets.QLabel(parent=self.title_bar)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lbl_subtitle.setFont(font)
        self.lbl_subtitle.setStyleSheet("color: #AAAAAA;")
        self.lbl_subtitle.setObjectName("lbl_subtitle")
        self.titles_layout.addWidget(self.lbl_subtitle)
        self.title_layout.addLayout(self.titles_layout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.title_layout.addItem(spacerItem)
        self.btn_nav_inspection = QtWidgets.QPushButton(parent=self.title_bar)
        self.btn_nav_inspection.setMinimumSize(QtCore.QSize(140, 45))
        self.btn_nav_inspection.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_nav_inspection.setObjectName("btn_nav_inspection")
        self.title_layout.addWidget(self.btn_nav_inspection)
        self.btn_nav_settings = QtWidgets.QPushButton(parent=self.title_bar)
        self.btn_nav_settings.setMinimumSize(QtCore.QSize(140, 45))
        self.btn_nav_settings.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_nav_settings.setObjectName("btn_nav_settings")
        self.title_layout.addWidget(self.btn_nav_settings)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.title_layout.addItem(spacerItem1)
        self.uni_layout = QtWidgets.QVBoxLayout()
        self.uni_layout.setSpacing(2)
        self.uni_layout.setObjectName("uni_layout")
        self.lbl_university = QtWidgets.QLabel(parent=self.title_bar)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        self.lbl_university.setFont(font)
        self.lbl_university.setStyleSheet("color: #E53935;")
        self.lbl_university.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_university.setObjectName("lbl_university")
        self.uni_layout.addWidget(self.lbl_university)
        self.lbl_faculty = QtWidgets.QLabel(parent=self.title_bar)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        self.lbl_faculty.setFont(font)
        self.lbl_faculty.setStyleSheet("color: #AAAAAA;")
        self.lbl_faculty.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_faculty.setObjectName("lbl_faculty")
        self.uni_layout.addWidget(self.lbl_faculty)
        self.lbl_clock = QtWidgets.QLabel(parent=self.title_bar)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lbl_clock.setFont(font)
        self.lbl_clock.setStyleSheet("color: #888888;")
        self.lbl_clock.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_clock.setObjectName("lbl_clock")
        self.uni_layout.addWidget(self.lbl_clock)
        self.title_layout.addLayout(self.uni_layout)
        self.main_layout.addWidget(self.title_bar)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_inspection = QtWidgets.QWidget()
        self.page_inspection.setObjectName("page_inspection")
        self.page1_layout = QtWidgets.QHBoxLayout(self.page_inspection)
        self.page1_layout.setProperty("margin", 0)
        self.page1_layout.setContentsMargins(0, 0, 0, 0)
        self.page1_layout.setObjectName("page1_layout")
        self.inspect_left_layout = QtWidgets.QVBoxLayout()
        self.inspect_left_layout.setSpacing(15)
        self.inspect_left_layout.setObjectName("inspect_left_layout")
        self.CAM_VIEW = QtWidgets.QFrame(parent=self.page_inspection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CAM_VIEW.sizePolicy().hasHeightForWidth())
        self.CAM_VIEW.setSizePolicy(sizePolicy)
        self.CAM_VIEW.setStyleSheet("border: 3px solid #00E676; background-color: #050505;")
        self.CAM_VIEW.setObjectName("CAM_VIEW")
        self.cam_view_layout = QtWidgets.QVBoxLayout(self.CAM_VIEW)
        self.cam_view_layout.setObjectName("cam_view_layout")
        self.lbl_monitor_inspect = QtWidgets.QLabel(parent=self.CAM_VIEW)
        self.lbl_monitor_inspect.setStyleSheet("border: none; background: transparent; color: #555555; font-size: 24px; font-weight: bold;")
        self.lbl_monitor_inspect.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_monitor_inspect.setObjectName("lbl_monitor_inspect")
        self.cam_view_layout.addWidget(self.lbl_monitor_inspect)
        self.inspect_left_layout.addWidget(self.CAM_VIEW)
        self.actions_layout = QtWidgets.QHBoxLayout()
        self.actions_layout.setSpacing(15)
        self.actions_layout.setObjectName("actions_layout")
        self.btn_start = QtWidgets.QPushButton(parent=self.page_inspection)
        self.btn_start.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_start.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_start.setObjectName("btn_start")
        self.actions_layout.addWidget(self.btn_start)
        self.btn_reset = QtWidgets.QPushButton(parent=self.page_inspection)
        self.btn_reset.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_reset.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_reset.setObjectName("btn_reset")
        self.actions_layout.addWidget(self.btn_reset)
        self.btn_stop = QtWidgets.QPushButton(parent=self.page_inspection)
        self.btn_stop.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_stop.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_stop.setObjectName("btn_stop")
        self.actions_layout.addWidget(self.btn_stop)
        self.inspect_left_layout.addLayout(self.actions_layout)
        self.page1_layout.addLayout(self.inspect_left_layout)
        self.inspect_right_layout = QtWidgets.QVBoxLayout()
        self.inspect_right_layout.setSpacing(15)
        self.inspect_right_layout.setObjectName("inspect_right_layout")
        self.tracking_log_group = QtWidgets.QGroupBox(parent=self.page_inspection)
        self.tracking_log_group.setMaximumSize(QtCore.QSize(480, 16777215))
        self.tracking_log_group.setStyleSheet("QGroupBox::title { color: #E53935; }")
        self.tracking_log_group.setObjectName("tracking_log_group")
        self.log_layout = QtWidgets.QVBoxLayout(self.tracking_log_group)
        self.log_layout.setObjectName("log_layout")
        self.table_tracking_log = QtWidgets.QTableWidget(parent=self.tracking_log_group)
        self.table_tracking_log.setAlternatingRowColors(True)
        self.table_tracking_log.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_tracking_log.setColumnCount(4)
        self.table_tracking_log.setObjectName("table_tracking_log")
        self.table_tracking_log.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_tracking_log.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tracking_log.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tracking_log.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tracking_log.setHorizontalHeaderItem(3, item)
        self.table_tracking_log.horizontalHeader().setStretchLastSection(True)
        self.log_layout.addWidget(self.table_tracking_log)
        self.log_btn_layout = QtWidgets.QHBoxLayout()
        self.log_btn_layout.setObjectName("log_btn_layout")
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.log_btn_layout.addItem(spacerItem2)
        self.btn_add_log = QtWidgets.QPushButton(parent=self.tracking_log_group)
        self.btn_add_log.setMinimumSize(QtCore.QSize(100, 35))
        self.btn_add_log.setObjectName("btn_add_log")
        self.log_btn_layout.addWidget(self.btn_add_log)
        self.btn_delete_log = QtWidgets.QPushButton(parent=self.tracking_log_group)
        self.btn_delete_log.setMinimumSize(QtCore.QSize(100, 35))
        self.btn_delete_log.setObjectName("btn_delete_log")
        self.log_btn_layout.addWidget(self.btn_delete_log)
        self.log_layout.addLayout(self.log_btn_layout)
        self.inspect_right_layout.addWidget(self.tracking_log_group)
        self.counter_group = QtWidgets.QGroupBox(parent=self.page_inspection)
        self.counter_group.setMaximumSize(QtCore.QSize(480, 300))
        self.counter_group.setObjectName("counter_group")
        self.gridLayout = QtWidgets.QGridLayout(self.counter_group)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_total = QtWidgets.QLabel(parent=self.counter_group)
        self.lbl_total.setObjectName("lbl_total")
        self.gridLayout.addWidget(self.lbl_total, 0, 0, 1, 1)
        self.lbl_ok_count = QtWidgets.QLabel(parent=self.counter_group)
        self.lbl_ok_count.setObjectName("lbl_ok_count")
        self.gridLayout.addWidget(self.lbl_ok_count, 0, 1, 1, 1)
        self.lbl_ng_count = QtWidgets.QLabel(parent=self.counter_group)
        self.lbl_ng_count.setObjectName("lbl_ng_count")
        self.gridLayout.addWidget(self.lbl_ng_count, 0, 2, 1, 1)
        self.lbl_yield = QtWidgets.QLabel(parent=self.counter_group)
        self.lbl_yield.setObjectName("lbl_yield")
        self.gridLayout.addWidget(self.lbl_yield, 0, 3, 1, 1)
        self.lcd_total_unit = QtWidgets.QLCDNumber(parent=self.counter_group)
        self.lcd_total_unit.setMinimumSize(QtCore.QSize(0, 50))
        self.lcd_total_unit.setDigitCount(5)
        self.lcd_total_unit.setObjectName("lcd_total_unit")
        self.gridLayout.addWidget(self.lcd_total_unit, 1, 0, 1, 1)
        self.lcd_pass = QtWidgets.QLCDNumber(parent=self.counter_group)
        self.lcd_pass.setMinimumSize(QtCore.QSize(0, 50))
        self.lcd_pass.setDigitCount(5)
        self.lcd_pass.setObjectName("lcd_pass")
        self.gridLayout.addWidget(self.lcd_pass, 1, 1, 1, 1)
        self.lcd_ng = QtWidgets.QLCDNumber(parent=self.counter_group)
        self.lcd_ng.setMinimumSize(QtCore.QSize(0, 50))
        self.lcd_ng.setDigitCount(5)
        self.lcd_ng.setObjectName("lcd_ng")
        self.gridLayout.addWidget(self.lcd_ng, 1, 2, 1, 1)
        self.lcd_yield = QtWidgets.QLCDNumber(parent=self.counter_group)
        self.lcd_yield.setMinimumSize(QtCore.QSize(0, 50))
        self.lcd_yield.setDigitCount(5)
        self.lcd_yield.setObjectName("lcd_yield")
        self.gridLayout.addWidget(self.lcd_yield, 1, 3, 1, 1)
        self.elapsed_layout = QtWidgets.QVBoxLayout()
        self.elapsed_layout.setObjectName("elapsed_layout")
        self.lbl_eslaped_count = QtWidgets.QLabel(parent=self.counter_group)
        self.lbl_eslaped_count.setObjectName("lbl_eslaped_count")
        self.elapsed_layout.addWidget(self.lbl_eslaped_count)
        self.lcd_elapsed = QtWidgets.QLCDNumber(parent=self.counter_group)
        self.lcd_elapsed.setMinimumSize(QtCore.QSize(0, 60))
        self.lcd_elapsed.setDigitCount(8)
        self.lcd_elapsed.setObjectName("lcd_elapsed")
        self.elapsed_layout.addWidget(self.lcd_elapsed)
        self.gridLayout.addLayout(self.elapsed_layout, 2, 0, 1, 2)
        self.lbl_result = QtWidgets.QLabel(parent=self.counter_group)
        self.lbl_result.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        self.lbl_result.setFont(font)
        self.lbl_result.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_result.setObjectName("lbl_result")
        self.gridLayout.addWidget(self.lbl_result, 2, 2, 1, 2)
        self.inspect_right_layout.addWidget(self.counter_group)
        self.page1_layout.addLayout(self.inspect_right_layout)
        self.stackedWidget.addWidget(self.page_inspection)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setObjectName("page_settings")
        self.page2_layout = QtWidgets.QVBoxLayout(self.page_settings)
        self.page2_layout.setProperty("margin", 0)
        self.page2_layout.setContentsMargins(0, 0, 0, 0)
        self.page2_layout.setObjectName("page2_layout")
        self.cb_device_list = QtWidgets.QComboBox(parent=self.page_settings)
        self.cb_device_list.setMinimumSize(QtCore.QSize(0, 35))
        self.cb_device_list.setCurrentText("")
        self.cb_device_list.setObjectName("cb_device_list")
        self.page2_layout.addWidget(self.cb_device_list)
        self.settings_main_layout = QtWidgets.QHBoxLayout()
        self.settings_main_layout.setSpacing(15)
        self.settings_main_layout.setObjectName("settings_main_layout")
        self.CAM_PREVIEW = QtWidgets.QFrame(parent=self.page_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CAM_PREVIEW.sizePolicy().hasHeightForWidth())
        self.CAM_PREVIEW.setSizePolicy(sizePolicy)
        self.CAM_PREVIEW.setStyleSheet("background-color: #050505; border: 1px solid #333333; border-radius: 8px;")
        self.CAM_PREVIEW.setObjectName("CAM_PREVIEW")
        self.preview_layout = QtWidgets.QVBoxLayout(self.CAM_PREVIEW)
        self.preview_layout.setObjectName("preview_layout")
        self.lbl_monitor_settings = QtWidgets.QLabel(parent=self.CAM_PREVIEW)
        self.lbl_monitor_settings.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_monitor_settings.setObjectName("lbl_monitor_settings")
        self.preview_layout.addWidget(self.lbl_monitor_settings)
        self.settings_main_layout.addWidget(self.CAM_PREVIEW)
        self.frame_settings_panel = QtWidgets.QFrame(parent=self.page_settings)
        self.frame_settings_panel.setMinimumSize(QtCore.QSize(320, 0))
        self.frame_settings_panel.setMaximumSize(QtCore.QSize(320, 16777215))
        self.frame_settings_panel.setObjectName("frame_settings_panel")
        self.settings_panel_layout = QtWidgets.QVBoxLayout(self.frame_settings_panel)
        self.settings_panel_layout.setSpacing(8)
        self.settings_panel_layout.setObjectName("settings_panel_layout")
        self.grp_init = QtWidgets.QGroupBox(parent=self.frame_settings_panel)
        self.grp_init.setObjectName("grp_init")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.grp_init)
        self.vboxlayout.setObjectName("vboxlayout")
        self.btn_search_dev = QtWidgets.QPushButton(parent=self.grp_init)
        self.btn_search_dev.setObjectName("btn_search_dev")
        self.vboxlayout.addWidget(self.btn_search_dev)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.btn_open_dev = QtWidgets.QPushButton(parent=self.grp_init)
        self.btn_open_dev.setObjectName("btn_open_dev")
        self.hboxlayout.addWidget(self.btn_open_dev)
        self.btn_close_dev = QtWidgets.QPushButton(parent=self.grp_init)
        self.btn_close_dev.setObjectName("btn_close_dev")
        self.hboxlayout.addWidget(self.btn_close_dev)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.settings_panel_layout.addWidget(self.grp_init)
        self.grp_acq = QtWidgets.QGroupBox(parent=self.frame_settings_panel)
        self.grp_acq.setObjectName("grp_acq")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.grp_acq)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.rad_continuous = QtWidgets.QRadioButton(parent=self.grp_acq)
        self.rad_continuous.setChecked(True)
        self.rad_continuous.setObjectName("rad_continuous")
        self.hboxlayout1.addWidget(self.rad_continuous)
        self.rad_trigger = QtWidgets.QRadioButton(parent=self.grp_acq)
        self.rad_trigger.setObjectName("rad_trigger")
        self.hboxlayout1.addWidget(self.rad_trigger)
        self.vboxlayout1.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.btn_acq_start = QtWidgets.QPushButton(parent=self.grp_acq)
        self.btn_acq_start.setObjectName("btn_acq_start")
        self.hboxlayout2.addWidget(self.btn_acq_start)
        self.btn_acq_stop = QtWidgets.QPushButton(parent=self.grp_acq)
        self.btn_acq_stop.setObjectName("btn_acq_stop")
        self.hboxlayout2.addWidget(self.btn_acq_stop)
        self.vboxlayout1.addLayout(self.hboxlayout2)
        self.hboxlayout3 = QtWidgets.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.chk_soft_trigger = QtWidgets.QCheckBox(parent=self.grp_acq)
        self.chk_soft_trigger.setObjectName("chk_soft_trigger")
        self.hboxlayout3.addWidget(self.chk_soft_trigger)
        self.btn_trigger_once = QtWidgets.QPushButton(parent=self.grp_acq)
        self.btn_trigger_once.setObjectName("btn_trigger_once")
        self.hboxlayout3.addWidget(self.btn_trigger_once)
        self.vboxlayout1.addLayout(self.hboxlayout3)
        self.settings_panel_layout.addWidget(self.grp_acq)
        self.grp_storage = QtWidgets.QGroupBox(parent=self.frame_settings_panel)
        self.grp_storage.setObjectName("grp_storage")
        self.gridlayout = QtWidgets.QGridLayout(self.grp_storage)
        self.gridlayout.setObjectName("gridlayout")
        self.btn_save_bmp = QtWidgets.QPushButton(parent=self.grp_storage)
        self.btn_save_bmp.setObjectName("btn_save_bmp")
        self.gridlayout.addWidget(self.btn_save_bmp, 0, 0, 1, 1)
        self.btn_save_jpg = QtWidgets.QPushButton(parent=self.grp_storage)
        self.btn_save_jpg.setObjectName("btn_save_jpg")
        self.gridlayout.addWidget(self.btn_save_jpg, 0, 1, 1, 1)
        self.btn_save_tiff = QtWidgets.QPushButton(parent=self.grp_storage)
        self.btn_save_tiff.setObjectName("btn_save_tiff")
        self.gridlayout.addWidget(self.btn_save_tiff, 1, 0, 1, 1)
        self.btn_save_png = QtWidgets.QPushButton(parent=self.grp_storage)
        self.btn_save_png.setObjectName("btn_save_png")
        self.gridlayout.addWidget(self.btn_save_png, 1, 1, 1, 1)
        self.settings_panel_layout.addWidget(self.grp_storage)
        self.grp_params = QtWidgets.QGroupBox(parent=self.frame_settings_panel)
        self.grp_params.setObjectName("grp_params")
        self.formlayout = QtWidgets.QFormLayout(self.grp_params)
        self.formlayout.setHorizontalSpacing(15)
        self.formlayout.setObjectName("formlayout")
        self.lbl_exp = QtWidgets.QLabel(parent=self.grp_params)
        self.lbl_exp.setObjectName("lbl_exp")
        self.formlayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_exp)
        self.txt_exposure = QtWidgets.QLineEdit(parent=self.grp_params)
        self.txt_exposure.setObjectName("txt_exposure")
        self.formlayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txt_exposure)
        self.lbl_gain = QtWidgets.QLabel(parent=self.grp_params)
        self.lbl_gain.setObjectName("lbl_gain")
        self.formlayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_gain)
        self.txt_gain = QtWidgets.QLineEdit(parent=self.grp_params)
        self.txt_gain.setObjectName("txt_gain")
        self.formlayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txt_gain)
        self.lbl_fps = QtWidgets.QLabel(parent=self.grp_params)
        self.lbl_fps.setObjectName("lbl_fps")
        self.formlayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_fps)
        self.txt_fps = QtWidgets.QLineEdit(parent=self.grp_params)
        self.txt_fps.setObjectName("txt_fps")
        self.formlayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txt_fps)
        self.lbl_fmt = QtWidgets.QLabel(parent=self.grp_params)
        self.lbl_fmt.setObjectName("lbl_fmt")
        self.formlayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_fmt)
        self.cb_pixel_fmt = QtWidgets.QComboBox(parent=self.grp_params)
        self.cb_pixel_fmt.setObjectName("cb_pixel_fmt")
        self.cb_pixel_fmt.addItem("")
        self.cb_pixel_fmt.addItem("")
        self.formlayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cb_pixel_fmt)
        self.btn_get_param = QtWidgets.QPushButton(parent=self.grp_params)
        self.btn_get_param.setObjectName("btn_get_param")
        self.formlayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.btn_get_param)
        self.btn_set_param = QtWidgets.QPushButton(parent=self.grp_params)
        self.btn_set_param.setObjectName("btn_set_param")
        self.formlayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btn_set_param)
        self.settings_panel_layout.addWidget(self.grp_params)
        self.grp_aux = QtWidgets.QGroupBox(parent=self.frame_settings_panel)
        self.grp_aux.setObjectName("grp_aux")
        self.hboxlayout4 = QtWidgets.QHBoxLayout(self.grp_aux)
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.btn_draw_circle = QtWidgets.QPushButton(parent=self.grp_aux)
        self.btn_draw_circle.setObjectName("btn_draw_circle")
        self.hboxlayout4.addWidget(self.btn_draw_circle)
        self.btn_draw_lines = QtWidgets.QPushButton(parent=self.grp_aux)
        self.btn_draw_lines.setObjectName("btn_draw_lines")
        self.hboxlayout4.addWidget(self.btn_draw_lines)
        self.settings_panel_layout.addWidget(self.grp_aux)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.settings_panel_layout.addItem(spacerItem3)
        self.settings_main_layout.addWidget(self.frame_settings_panel)
        self.page2_layout.addLayout(self.settings_main_layout)
        self.stackedWidget.addWidget(self.page_settings)
        self.main_layout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QC_PCB INSPECTION SYSTEM"))
        self.lbl_logo.setText(_translate("MainWindow", "i"))
        self.lbl_title.setText(_translate("MainWindow", "HỆ THỐNG KIỂM TRA CHẤT LƯỢNG MẠCH"))
        self.lbl_subtitle.setText(_translate("MainWindow", "QC_PCB INSPECTION SYSTEM"))
        self.btn_nav_inspection.setText(_translate("MainWindow", "Theo dõi"))
        self.btn_nav_settings.setText(_translate("MainWindow", "CÀI ĐẶT CAMERA"))
        self.lbl_university.setText(_translate("MainWindow", "ĐẠI HỌC PHENIKAA"))
        self.lbl_faculty.setText(_translate("MainWindow", "TRƯỜNG KỸ THUẬT - KHOA CƠ ĐIỆN TỬ"))
        self.lbl_clock.setText(_translate("MainWindow", "16:29:30 - 05/05/2026"))
        self.lbl_monitor_inspect.setText(_translate("MainWindow", "NO CAMERA SIGNAL"))
        self.btn_start.setText(_translate("MainWindow", "START PROCESS"))
        self.btn_reset.setText(_translate("MainWindow", "RESET"))
        self.btn_stop.setText(_translate("MainWindow", "EMERGENCY STOP"))
        self.tracking_log_group.setTitle(_translate("MainWindow", "ERROR TRACKING LOG"))
        item = self.table_tracking_log.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Defect ID"))
        item = self.table_tracking_log.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Error Type"))
        item = self.table_tracking_log.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Component"))
        item = self.table_tracking_log.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Location"))
        self.btn_add_log.setText(_translate("MainWindow", "Add"))
        self.btn_delete_log.setText(_translate("MainWindow", "Delete"))
        self.counter_group.setTitle(_translate("MainWindow", "COUNTER RESULTS"))
        self.lbl_total.setStyleSheet(_translate("MainWindow", "color:#00E676;font-weight:bold;"))
        self.lbl_total.setText(_translate("MainWindow", "TOTAL"))
        self.lbl_ok_count.setStyleSheet(_translate("MainWindow", "color:#00E676;font-weight:bold;"))
        self.lbl_ok_count.setText(_translate("MainWindow", "PASS"))
        self.lbl_ng_count.setStyleSheet(_translate("MainWindow", "color:#E53935;font-weight:bold;"))
        self.lbl_ng_count.setText(_translate("MainWindow", "NG"))
        self.lbl_yield.setStyleSheet(_translate("MainWindow", "color:#42A5F5;font-weight:bold;"))
        self.lbl_yield.setText(_translate("MainWindow", "YIELD %"))
        self.lcd_ng.setStyleSheet(_translate("MainWindow", "color: #E53935; border-color: #E53935;"))
        self.lcd_yield.setStyleSheet(_translate("MainWindow", "color: #42A5F5; border-color: #42A5F5;"))
        self.lbl_eslaped_count.setStyleSheet(_translate("MainWindow", "color:#AAAAAA;font-weight:bold;"))
        self.lbl_eslaped_count.setText(_translate("MainWindow", "ELAPSED TIME"))
        self.lcd_elapsed.setStyleSheet(_translate("MainWindow", "color: #42A5F5; border-color: #42A5F5;"))
        self.lbl_result.setStyleSheet(_translate("MainWindow", "background-color: #1A1A2E; color: #888888; border: 2px solid #444444; border-radius: 6px; margin-top:10px;"))
        self.lbl_result.setText(_translate("MainWindow", "WAITING..."))
        self.lbl_monitor_settings.setStyleSheet(_translate("MainWindow", "color: #555555; font-size: 20px; font-weight: bold; border: none;"))
        self.lbl_monitor_settings.setText(_translate("MainWindow", "CAMERA PREVIEW"))
        self.grp_init.setTitle(_translate("MainWindow", "Initialization"))
        self.btn_search_dev.setText(_translate("MainWindow", "Search Device"))
        self.btn_open_dev.setText(_translate("MainWindow", "Open Device"))
        self.btn_close_dev.setText(_translate("MainWindow", "Close Device"))
        self.grp_acq.setTitle(_translate("MainWindow", "Image Acquisition"))
        self.rad_continuous.setText(_translate("MainWindow", "Continuous"))
        self.rad_trigger.setText(_translate("MainWindow", "Trigger Mode"))
        self.btn_acq_start.setStyleSheet(_translate("MainWindow", "background-color:#00C853; font-weight:bold;"))
        self.btn_acq_start.setText(_translate("MainWindow", "Start"))
        self.btn_acq_stop.setStyleSheet(_translate("MainWindow", "background-color:#E53935; font-weight:bold;"))
        self.btn_acq_stop.setText(_translate("MainWindow", "Stop"))
        self.chk_soft_trigger.setText(_translate("MainWindow", "Trigger by Software"))
        self.btn_trigger_once.setText(_translate("MainWindow", "Trigger Once"))
        self.grp_storage.setTitle(_translate("MainWindow", "Picture Storage"))
        self.btn_save_bmp.setText(_translate("MainWindow", "Save as BMP"))
        self.btn_save_jpg.setText(_translate("MainWindow", "Save as JPG"))
        self.btn_save_tiff.setText(_translate("MainWindow", "Save as TIFF"))
        self.btn_save_png.setText(_translate("MainWindow", "Save as PNG"))
        self.grp_params.setTitle(_translate("MainWindow", "Parameters"))
        self.lbl_exp.setText(_translate("MainWindow", "Exposure Time"))
        self.txt_exposure.setText(_translate("MainWindow", "800"))
        self.lbl_gain.setText(_translate("MainWindow", "Gain"))
        self.txt_gain.setText(_translate("MainWindow", "0"))
        self.lbl_fps.setText(_translate("MainWindow", "Frame Rate"))
        self.txt_fps.setText(_translate("MainWindow", "10"))
        self.lbl_fmt.setText(_translate("MainWindow", "Pixel Format"))
        self.cb_pixel_fmt.setItemText(0, _translate("MainWindow", "BGR8Packed"))
        self.cb_pixel_fmt.setItemText(1, _translate("MainWindow", "Mono8"))
        self.btn_get_param.setText(_translate("MainWindow", "Get Parameter"))
        self.btn_set_param.setStyleSheet(_translate("MainWindow", "border-color:#42A5F5; color:#42A5F5;"))
        self.btn_set_param.setText(_translate("MainWindow", "Set Parameter"))
        self.grp_aux.setTitle(_translate("MainWindow", "Auxiliary Line Drawing"))
        self.btn_draw_circle.setText(_translate("MainWindow", "Draw Circle"))
        self.btn_draw_lines.setText(_translate("MainWindow", "Draw Lines"))
